<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="ModelContextProtocol" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
      <ProjectReference Include="..\Assistant\Assistant.csproj" />
      <ProjectReference Include="..\Opensearch\Opensearch.csproj" />
    </ItemGroup>

</Project>